version: "3.8"
services:
  resolver:
    build: .
    environment:
      - GIN_MODE=debug
      - RESOLVER_LOG_LEVEL=debug
      - RESOLVER_SERVICE_NAME=resoverGeolite
      - TELEMETRY_DISABLED=true
    ports:
      - 7000:7000
    env_file:
      - .env
